spring:
  mail:
    host: smtp.gmail.com
    username: transactionalerts29@gmail.com
    password: fvbaqfsysicrzfza
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true